workspace:
  base: /vue
  path: concept

clone:
  git:
    image: plugins/git
    depth: 52
    tags: true

pipeline:
  ssh:
    image: appleboy/drone-ssh
    host:
      - digitalocean.c1495616.com
    username: root
    password: jerry210492
    script:
      - echo "HI"
